### ISSUE TITLE
Support all crafting stations (Anvil, Enchanting, Smithing, Stonecutter, etc)

### ISSUE THREAD

**Issue by Folas1337** [percyqaz/Shulkerbox#3]
I'd like to request more blocks to be added that you can right click in the inventory to interact with them, like the ones mentioned in the title and also anvils, cartography tables and more.

For anvils I'm not sure how to deal with the random damage it can receive, maybe skip them or perhaps add a feature so they turn into a worse version for the vanilla chance?

Feel free to take this suggestion as you want, you don't have to add anything but you can add as many as you want, I mean I can't force you anyway :D

**Comment by percyqaz** [comment]
This is a great request - I've been thinking of at least adding stonecutters because it would be so helpful while building

Here's the full list I think would be worth adding:
- Stonecutter
- Grindstone IF I can get the xp to be dropped properly when disenchanting
- Cartography table
- Loom
- Smithing table

Others that could be added but I'm not sure about:
- Anvils
- Enchanting tables
For both of these the blocks interact with the world in some way

Enchanting tables need bookshelves around them for maximum enchanting power, and I wouldn't want them to be max level when used from the inventory. But then making them only able to do level 1-3 enchantments makes it a pretty useless feature

Anvils could receive random damage as you've pointed out. Adding damage to the anvil while it's in the inventory sounds simple but is actually about the same difficulty as the main feature of opening and editing shulker boxes (I have to think about what happens when it's a stack of anvils, or if you move the slot the anvil is in while using it, for example)

So I think I will skip enchanting tables and anvils for now since I don't think it's worth the effort

For the others, I'll investigate what can be done (possibly this weekend)

**Comment by IceX2457** [comment]
Well for the enchanting table I can see you checking the number of bookshelves in the inv of the person, i guess it would be easier then for it to interact with the world like idk the level of enchantments per book but like if bookshelves is 1 then this lvl enchants etc etc and on the end of course bookshelves >= 15 because you can have more. (Might be a hard one but I think it's easier then trying to interact with the world)

**Comment by percyqaz** [comment]
> Well for the enchanting table I can see you checking the number of bookshelves in the inv of the person

You make a good point, I also thought of this right after posting my previous comment

I'll still shy away from enchanting tables for now because it's not as simple as the others
Users may not naturally understand that they need bookshelves in the same inventory, since every other feature of this plugin just involves right-clicking on a self-contained item, so there could be a better way if I spend some more time thinking about it

----

I've done some investigation into opening blocks like the stonecutter, unfortunately Spigot doesn't properly support opening these other inventories like it does for a workbench

There is a plugin that lets you open these inventories (including ones that store data like furnaces) [here](https://www.spigotmc.org/resources/portable-crafting-inventories-completely-customizable.61045/field?field=documentation) by running commands, but the way it works is to tie the plugin's code directly to the Minecraft code for that version of the game.
This means the plugin needs to be manually updated for every version of Minecraft it supports (since the code it directly linked to has changed and it won't load otherwise)

If this turns out to be the only way of opening these inventories, I don't know if I'll be willing to add the features, because it means extra work for me whenever a new minecraft version comes out, rather than the plugin automatically being compatible with future versions

I'll keep tinkering this weekend and see what happens

**Comment by percyqaz** [comment]
Good news!
PaperMC's API is more extensive than Spigot's, and it has proper support for opening these crafting inventories, so I can easily add support now

The drawback is that the plugin, or at least these features, will not work if you use Spigot as your Minecraft server

My plan is to add these features and have them automatically turned off if you are not using Paper, so that the plugin at least still works the same as it does now if you use Spigot

I'm busy for the rest of today but it might be done as soon as tomorrow, we'll see :)

**Comment by Folas1337** [comment]
I'm the owner, ice is one of my users and I'm running paper everywhere (of course). So I'm all for this, go right ahead!! 🎉

**Comment by percyqaz** [comment]
It is done!
You can get the latest release [here](https://github.com/percyqaz/Shulkerbox/releases/tag/1.3) - Spigot users will have these features disabled because it relies on Paper's expanded API as mentioned above

I will write the enchanting table and anvil requests as separate issues with a bit more detail to remind me to come back to them
